Test/Controllers/GraphsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test;
using Test.BLL;

namespace Test.Controllers
{
    public class GraphsController : Controller
    {
        private readonly TestDbContext _context;

        public GraphsController(TestDbContext context)
        {
            _context = context;
        }

        // GET: Graphs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Graphs.ToListAsync());
        }

        // GET: Graphs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .SingleOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // GET: Graphs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Graphs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Graph graph)
        {
            if (ModelState.IsValid)
            {
                _context.Add(graph);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(graph);
        }

        // GET: Graphs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs.SingleOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }
            return View(graph);
        }

        // POST: Graphs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Graph graph)
        {
            if (id != graph.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(graph);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GraphExists(graph.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(graph);
        }

        // GET: Graphs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .SingleOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // POST: Graphs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var graph = await _context.Graphs.SingleOrDefaultAsync(m => m.Id == id);
            _context.Graphs.Remove(graph);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> TopoAsync(int id)
        {
            var graph = await _context.Graphs.SingleOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            var topoSorter = new TopoSorter();
            var nodes = topoSorter.Sort(graph);

            return View(nodes);
        }

        private bool GraphExists(int id)
        {
            return _context.Graphs.Any(e => e.Id == id);
        }
    }
}

Test/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test;
using Test.BLL;
using Test.Models;

namespace Test.Controllers
{
    public class NodesController : Controller
    {
        private readonly TestDbContext _context;

        public NodesController(TestDbContext context)
        {
            _context = context;
        }

        // GET: Nodes
        public async Task<IActionResult> Index(int graphId)
        {
            ViewBag.GraphId = graphId;
            var graph = _context.Graphs.SingleOrDefault(x=>x.Id == graphId);

            return View(graph.Nodes);
        }

        // GET: Nodes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await _context.Node
                .SingleOrDefaultAsync(m => m.Id == id);
            if (node == null)
            {
                return NotFound();
            }

            return View(node);
        }

        // GET: Nodes/Create
        public IActionResult Create(int graphId)
        {
            ViewBag.GraphId = graphId;
            return View();
        }

        // POST: Nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Node node, int graphId)
        {
            if (ModelState.IsValid)
            {
                var graph = _context.Graphs.SingleOrDefault(x => x.Id == graphId);
                if (graph.Nodes == null)
                {
                    graph.Nodes = new List<Node>();
                }

                graph.Nodes.Add(node);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { graphId });
            }
            return View(node);
        }

        // GET: Nodes/Edit/5
        public async Task<IActionResult> Edit(int? id, int graphId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await _context.Node.SingleOrDefaultAsync(m => m.Id == id);
            if (node == null)
            {
                return NotFound();
            }
            return View(node);
        }

        // POST: Nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int graphId, [Bind("Id,Name")] Node node)
        {
            if (id != node.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(node);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NodeExists(node.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.GraphId = graphId;

                return RedirectToAction(nameof(Index));
            }
            return View(node);
        }

        // GET: Nodes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await _context.Node
                .SingleOrDefaultAsync(m => m.Id == id);
            if (node == null)
            {
                return NotFound();
            }

            return View(node);
        }

        // POST: Nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var node = await _context.Node.SingleOrDefaultAsync(m => m.Id == id);
            _context.Node.Remove(node);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Relations(int id, int graphId)
        {
            var graph = _context.Graphs.SingleOrDefault(x => x.Id == graphId);
            var node = _context.Node.SingleOrDefault(x => x.Id == id);
            var models = new List<RelatedNodeViewModel>();
            var relatedModels = node.Nodes.Select(x => new RelatedNodeViewModel {
                Node = x,
                IsRelated = true
            });
            models.AddRange(relatedModels);

            var graphModels = graph.Nodes
                .Where(x=> x != node && !node.Nodes.Contains(x))
                .Select(x=> new RelatedNodeViewModel
            {
                Node = x,
                IsRelated = false
            });
            models.AddRange(graphModels);

            ViewBag.GraphId = graphId;
            ViewBag.NodeId = id;

            return View(models);
        }

        public IActionResult SwitchRelation(int id, int graphId, int relationId)
        {
            var graph = _context.Graphs.SingleOrDefault(x => x.Id == graphId);
            var node = _context.Node.SingleOrDefault(x => x.Id == id);
            var relatedNode = node.Nodes.SingleOrDefault(x => x.Id == relationId);
            if (relatedNode == null)
            {
                relatedNode = graph.Nodes.SingleOrDefault(x => x.Id == relationId);
                node.Nodes.Add(relatedNode);
            }
            else
            {
                node.Nodes.Remove(relatedNode);
            }

            _context.SaveChanges();

            ViewBag.GraphId = graphId;
            ViewBag.NodeId = id;

            return RedirectToAction(nameof(Relations), new { id, graphId });
        }

        private bool NodeExists(int id)
        {
            return _context.Node.Any(e => e.Id == id);
        }
    }
}

Test/Views/Graphs/Create.cshtml
@model Test.BLL.Graph

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Graph</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Test/Views/Graphs/Delete.cshtml
@model Test.BLL.Graph

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Graph</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Test/Views/Graphs/Details.cshtml
@model Test.BLL.Graph

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Graph</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Test/Views/Graphs/Edit.cshtml
@model Test.BLL.Graph

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Graph</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Test/Views/Graphs/Index.cshtml
@model IEnumerable<Test.BLL.Graph>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Index" asp-controller="Nodes" asp-route-graphId="@item.Id">Nodes</a> |
                <a asp-action="TopoAsync" asp-route-id="@item.Id">Topo</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Test/Views/Graphs/TopoAsync.cshtml
@model Test.BLL.Node[]

@{
    ViewBag.Title = "Topo";
    Layout = "_Layout";
}

<h2>Topo</h2>
@foreach (var node in Model)
{
    <div>
        @node.Name
    </div>
}